# You can enable config/features that affect all services here.
global:
  k8s:
    # -- This is the value of your clusters `kubeadm init --service-dns-domain` flag
    clusterDomain: cluster.local
  spire:
    # -- The name of the Kubernetes cluster (`kubeadm init --service-dns-domain`)
    clusterName: example-cluster
    # -- The trust domain to be used for the SPIFFE identifiers
    trustDomain: example.org
    # -- Override all instances of bundleConfigMap
    bundleConfigMap: ""

    image:
      # -- Override all Spire image registries at once
      registry: ""

#  telemetry:
#    prometheus:
#      enabled: true
#      podMonitor:
#        enabled: true
#        # -- Allows to install the PodMonitor in another namespace then the spire components are installed into.
#        namespace: "kube-prometheus-system"
#        labels: {}

# subcharts
spire-server:
  # -- Enables deployment of SPIRE Server
  enabled: true
  nameOverride: server

  image:
    registry: ""
    repository: "spire-server"
    tag: "latest-local"

  dataStore:
    sql:
      # -- Other supported databases are "postgres" and "mysql"
      databaseType: mysql
      # -- Only used by "postgres" or "mysql"
      databaseName: spire
      # -- Only used by "postgres" or "mysql"
      host: "mysql.default.svc"
      # -- If 0 (default), it will auto set to 5432 for postgres and 3306 for mysql. Only used by those databases.
      port: 0
      # -- Only used by "postgres" or "mysql"
      username: root
      # -- Only used by "postgres" or "mysql"
      password: "password"
      # -- Only used by "postgres" or "mysql"
      options:
        - parseTime: true
          #- a: "b"

      # -- Settings from https://github.com/spiffe/spire/blob/main/doc/plugin_server_datastore_sql.md go in this section
      plugin_data: {}

  controllerManager:
    # -- Enables deployment of Controller Manager
    enabled: true

spire-agent:
  # -- Enables deployment of SPIRE Agent(s)
  enabled: true
  nameOverride: agent

spiffe-csi-driver:
  # -- Enables deployment of CSI driver
  enabled: true

spiffe-oidc-discovery-provider:
  # -- Enables deployment of OIDC discovery provider
  enabled: false

tornjak-frontend:
  # -- Enables deployment of Tornjak frontend/UI (Not for production)
  enabled: false
