name: Helm Chart CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/helm-chart-ci.yaml'
      - '.github/kind/conf/kind-config.yaml'
      - '.github/tests/**/*.yaml'
      - '.github/tests/**/*.sh'
      - '.github/tests/**/*.json'
      - 'examples/**/*.yaml'
      - 'helm-docs.sh'

jobs:
  lint-chart:
    runs-on: ubuntu-22.04
    steps:
      - run: 'echo "Skipping linter"'

  checks:
    runs-on: ubuntu-22.04
    steps:
      - run: 'echo "Skipping checks"'

  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k8s:
          - v1.27.0
          - v1.26.3
          - v1.25.8
        values:
          - default
          - extras
          - namespace-override
          - production-example
    steps:
      - run: 'echo "Skipping tests"'
